<?php

namespace Apollo\Repository;

use Doctrine\ORM\EntityRepository;
use Apollo\Entity\Departement;

/**
 * DepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends EntityRepository
{

}