<?php

namespace Apollo\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FinancementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancementRepository extends EntityRepository
{

}