<?php

namespace Apollo\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FractionnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FractionnementRepository extends EntityRepository
{

}