<?php

namespace Apollo\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NegociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NegociationRepository extends EntityRepository
{

  public function findAllNego(Array $orderBy)
  {
    return $this->findBy(array(), $orderBy);
  }
}