<?php

namespace Apollo\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PieceJointeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceJointeRepository extends EntityRepository
{

}