<?php

namespace Apollo\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PjTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PjTypeRepository extends EntityRepository
{

}