<?php

namespace Apollo\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SousNegoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousNegoRepository extends EntityRepository
{

}