<?php

namespace Apollo\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StatusFinancementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusFinancementRepository extends EntityRepository
{

}