<?php

namespace Apollo\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeNegoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeNegoRepository extends EntityRepository
{

}